pre-commit:
  parallel: true
  commands:
    format:
      run: cd app && bunx biome format --write .
      stage_fixed: true
    lint:
      run: cd app && bun run lint
      fail_text: 'Linting failed. Please fix the errors above before committing.'
