/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreviewJdIdRouteImport } from './routes/preview/$jdId'
import { Route as DetailJdIdRouteImport } from './routes/detail/$jdId'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewJdIdRoute = PreviewJdIdRouteImport.update({
  id: '/preview/$jdId',
  path: '/preview/$jdId',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailJdIdRoute = DetailJdIdRouteImport.update({
  id: '/detail/$jdId',
  path: '/detail/$jdId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/detail/$jdId': typeof DetailJdIdRoute
  '/preview/$jdId': typeof PreviewJdIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/detail/$jdId': typeof DetailJdIdRoute
  '/preview/$jdId': typeof PreviewJdIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/detail/$jdId': typeof DetailJdIdRoute
  '/preview/$jdId': typeof PreviewJdIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mcp' | '/detail/$jdId' | '/preview/$jdId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mcp' | '/detail/$jdId' | '/preview/$jdId'
  id: '__root__' | '/' | '/mcp' | '/detail/$jdId' | '/preview/$jdId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  McpRoute: typeof McpRoute
  DetailJdIdRoute: typeof DetailJdIdRoute
  PreviewJdIdRoute: typeof PreviewJdIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$jdId': {
      id: '/preview/$jdId'
      path: '/preview/$jdId'
      fullPath: '/preview/$jdId'
      preLoaderRoute: typeof PreviewJdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detail/$jdId': {
      id: '/detail/$jdId'
      path: '/detail/$jdId'
      fullPath: '/detail/$jdId'
      preLoaderRoute: typeof DetailJdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  McpRoute: McpRoute,
  DetailJdIdRoute: DetailJdIdRoute,
  PreviewJdIdRoute: PreviewJdIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
